### ISSUE TITLE
Varptr and constant addresses

### ISSUE THREAD

**Issue by artrag** [nanochess/IntyBASIC#1]
In my developments in INTYBASIC I have the following line that involves two constants and one variable
nn = (varptr shoot_v(0)-varptr shoot_n(0))-sfxstep

The compiled code works fine but looks like this:

;[249] 	nn = (varptr shoot_v(0)-varptr shoot_n(0))-sfxstep
                                	SRCFILE "ISR.BAS",249
678F   02B8 67C5                	MVII #Q176,R0
6791   02B9 67BF                	MVII #Q177,R1
6793   0108                     	SUBR R1,R0
6794   0300 016B                	SUB V1,R0
6796   0240 0162                	MVO R0,V80

Provided that this expression 
(varptr shoot_v(0)-varptr shoot_n(0)) 
is constant at compilation time, and incidentally it is equal to 6, I would have expected that the compiler was able to resolve the computation generating something like this:

MVO 6,R0             ; R0=6
SUB V1,R0            ; R0 = R0-V1
MVO R0,V80        ; V80 = R0

Let me know what you think about it
AR

PS
I'm guessing the meaning of the opcodes  ;-)

**Comment by intvnut** [comment]
The sequence would actually be:

    MVII #6, R0      ; MVII means "move in immediate", as in "put immediate value in register"
    SUB V1, R0
    MVO R0, V80   ; MVO means "move out", as in "write to memory"

I don't think IntyBASIC knows what Q177 - Q176 is at compile time, at least not in the general case, as these labels may not have been reached yet and IntyBASIC is a single-pass compiler.  But, it could theoretically output an expression that the assembler could evaluate at assembly time:

    MVII #Q177 - Q176, R0
    SUB V1, R0
    MVO R0, V80

I don't know how feasible that is for Óscar to implement, but that might be the appropriate strategy to stay in a single-pass compilation model.

**Comment by nanochess** [comment]
Actually there is code of array optimization (different array same index) that uses that syntax, so I've implemented it for that very special case of VARPTR array1(x) - VARPTR array2(y) where x and y are constants.
