### ISSUE TITLE
Button testing

### ISSUE THREAD

**Issue by artrag** [nanochess/IntyBASIC#13]
[audio.zip](https://github.com/nanochess/IntyBASIC/files/2716820/audio.zip)

Try to run the attached AUDIO.BAS in v129 and press any button
The SFX for Galaxian will start

In v140 the attached code does not detect the pression of the side buttons
I cannot say why, but comparing the ASM it seems that  TST opcode is missing

**Comment by nanochess** [comment]
Hi. I've tested your sample program. Your loading of t0, t1 and t2 at end of loop with too many WAIT makes it hard to detect your depressing if it happens between these WAIT. I've replaced the 4 WAIT with only one. Then all the PRINT are slow and probably exceed frame time, so first moved T0, T1 and T2 assignment before the bunch of PRINT and then remove most of them. So now your program works with good response.
[audio.txt](https://github.com/nanochess/IntyBASIC/files/2739227/audio.txt)

**Comment by artrag** [comment]
I see your point. My code even if you press the buttons for 4 frames can detect their release only in the last frame when the buttons have been tested.
It make sense, but if compiled in v129, (now It'd say strangely!) it works just fine.... 
Anyway thanks !
