### ISSUE TITLE
memory layout and segment management

### ISSUE THREAD

**Issue by artrag** [nanochess/IntyBASIC#2]
The most critical things I'm facing while developing in intybasic is the fact that there is almost no easy control on the way memory is used and it is very easy to fill a segment of rom without being able to trace what is going wrong and what could be done to solve the issue.
I know that intybasic generates only ASM files and that actual rom allocation is defined at assembly time, nevertheless some information to support the coder while detecting this kind of problems could be included in the assembly generated by Intybasic.

I would find useful, for example, generating labels with the start address and the size of procedures and blocks of data with a naming convention easy to extract from the LST file.
Joe Zbiciak was telling of an assembly system based on macros called cart.mac able to detect at assembly time if there are mapping problems.
Maybe it could be another option....

**Comment by artrag** [comment]
As matter of fact, this version of deep zone has started suddenly to crash at boot time, but I'm not able to detect what is failing.
It has to to with overwriting some critical part of the Intybasic support code, as I cannot see neither the boot, but from the analysis of the CFG and of the LST, apparently I cannot see overflow of rom segments


[dzgorf2018_04_19_nowork.zip](https://github.com/nanochess/IntyBASIC/files/1927038/dzgorf2018_04_19_nowork.zip)

**Comment by artrag** [comment]
I have isolated the problem. It is RAND(6) at line 1792 in dzgorf.bas that is causing a memory layout (??) problem that in turn is causing a crash at boot time.
The attached version here works perfectly, where I have replaced RAND(6) at line 1792 with a constant value. 
If you compare this working version with the previous version, the sole difference is RAND(6) at line 1792.
Comparing the two LST files I'm not able to get what is causing the boot error and I'm not even sure anymore about the real cause of the issue... Could it be a nasty Intybasic bug ?

[dzgorf2018_04_19_working.zip](https://github.com/nanochess/IntyBASIC/files/1927869/dzgorf2018_04_19_working.zip)

**Comment by nanochess** [comment]
Every IntyBASIC program starts automatically at $5000-$6fff because this is the address where Intellivision searchs for a cartridge. The other zones available are $2100-$2fff, $4810-$4fff, $7100-$7fff,$a000-$bfff and $c100-$ffff.

If you get confused I would suggest removing all your ASM ORG, then compiling and checking the LST file and search the first limit address ($6fff), once you find it, insert an ASM ORG to make following code to fit, repeat till all your code fit succesfully.

If you have many data files with known size, it's easier to fit them into the available zones without checking the LST file. Each DATA value corresponds to a word, so in $a000-$bfff (for example) there is space for 8192 words, or 8192 DATA items.

I tend to put DATA files in the small segments and put my last ORG at $c100, remember the intybasic epilogue assembler file uses almost 2K words (depending on what features are you using)

**Comment by artrag** [comment]
hi Oscar
I'm using these ranges

$2100 - $2FFF,
$4810 - $4FFF,
$5000 - $6FFF,
$7100 - $7FFF,
$8040 - $BFFF,
$C040 - $FFFF

and these org's:

	ASM ORG $A000
	ASM ORG $C040
	ASM ORG $2100
	ASM ORG $7100
	ASM ORG $8040
	ASM ORG $4810

Could it be that the segment at $4810 is too small for intybasic's epilogue and it overlaps with the game code at $5000?

**Comment by artrag** [comment]
Yes, it was the epilogues that under certain conditions passes the $5000 limit.
I have to move it in a larger segment.

**Comment by artrag** [comment]
Maybe, if AS1600 could warn the user when two segments of data/code overlap, there would be a chance to spot this kind pf problems with less headaches...

**Comment by intvnut** [comment]
I will be able to spend some time investigating such a feature / pragma in AS1600 this weekend.  I would make the feature available to all.

I do make creative use of re-writing memory in AS1600, but usually it's an error.  I don't want to break existing codebases, so I will likely make it opt-in in AS1600; however, a future IntyBASIC release could turn it on by default.

I will use the existing feature define mechanism to advertise the feature's availability, so you can produce assembly code that will work with old and new assemblers.

**Comment by intvnut** [comment]
I just checked in some code that will check for this error in the assembler, along with a couple directives to control it.  The quick and dirty method, though, is just to add a new flag to the command line:

$ as1600 -e asm/dzgorf.asm -o bin/dzgorf.bin 
asm/dzgorf.asm:58501: ERROR - ROM overwrite error on $5000 - $5054
