### ISSUE TITLE
Bug in  DATA statement  whe VARPTR is used

### ISSUE THREAD

**Issue by artrag** [nanochess/IntyBASIC#24]
Apparently this piece of code works
	DATA 	VARPTR attribute_r1(0),VARPTR attribute_r2(0),VARPTR attribute_r3(0)
but not this other where VARPTR is used in minuscule letters
	DATA 	varptr attribute_r1(0),varptr attribute_r2(0),varptr attribute_r3(0)

Is it a bug ?

**Comment by nanochess** [comment]
Just got a look and it works correctly. Internally the comparison with "VARPTR" automatically nullifies case.
