### ISSUE TITLE
DEFINE VARPTR and DEFINE varprt

### ISSUE THREAD

**Issue by artrag** [nanochess/IntyBASIC#25]
It seems that the capital letters are mandatory when using varprt with define
This command (at line 385)
	define 15,1,varprt #softbullets(3)
gives 
Warning: invalid extra characters in line 385
Error: label 'VARPRT' undefined
Same for 
	DEFINE 15,1,varprt #softbullets(3)

Only 
	DEFINE 15,1,VARPTR #softbullets(3)
works as expected

**Comment by nanochess** [comment]
Lowercase is also accepted, but instead of varptr you wrote varprt.
