### ISSUE TITLE
DEFINE and DEFINE ALTERNATE

### ISSUE THREAD

**Issue by artrag** [nanochess/IntyBASIC#5]
I find a bit off how DEFINE  and DEFINE ALTERNATE works. 
You can only change TWO sets of tiles per frame even if you are within the limit of 16 tiles/frame.
I understand that extending the number of sets would have used precious ram.
Nevertheless maybe something could be improved even if you stay with just two "transfer slots" per frame. 
Now in my code I cannot say if I have to use DEFINE,  DEFINE ALTERNATE to initialize a given set of tiles, of if I have to postpone that update to the next frame, because I do not know in advance if previous sections of code have already booked or not a transfer slot.
This because in deep zone the speed of different game elements increases level by level, so, it is hard to say if and who will try to take a transfer slot in a given frame.

What about using a function in place of define as statement, able to say if the "booking" has been taken or not ?
Something able allow to code like this:

         if (counter1<0) and (DEFINE(card_num1,total1,label1)) then 

            BOOKING OK: counter1 = rate1

         else

            counter1 = counter1 + 1; ' DELAY THIS UPDATE TO NEXT FRAME

         end

         if (counter2<0) and (DEFINE(card_num2,total2,label2)) then 

            BOOKING OK: counter2 = rate2

         else

            counter2 = counter1 + counter2 + 1; ' DELAY THIS UPDATE TO NEXT FRAME

         end
 
         if (counter3<0) and (DEFINE(card_num3,total3,label3)) then 

            BOOKING OK: counter3 = rate3

         else

            counter3 = counter2 + counter3 + 1; ' DELAY THIS UPDATE TO NEXT FRAME

         end

etc etc

**Comment by nanochess** [comment]
If I'm understanding right then you have 4 GRAM updates, you could separate it in two GRAM updates per frame.

IF FRAME AND 1 THEN
     DEFINE
     DEFINE ALTERNATE
ELSE
     DEFINE
     DEFINE ALTERNATE
END IF

I've been thinking in solutions for sparse GRAM definition but haven't got to a solution yet.

**Comment by artrag** [comment]
No, my problem is that I cannot know when a define will be needed, as the speed of any game element varies. I was thinking to something like this:

mainloop:

wait

flag = 0 : ' bit 0 DEFINE is booked, bit 1 ALTERNATE DEFINE is used

if stars_need_update then
if (flag and 3 = 3) then 
    postpone update for stars
else if (flag and 1) then
   DEFINE stars: flag = flag or 1
else if (flag and 2) then
  ALTERNATE DEFINE stars: flag = flag or 2
end if
end if

if main_ship_needs_update then
if (flag and 3 = 3) then 
    postpone update for main ship
else if (flag and 1) then
   DEFINE main ship: flag = flag or 1
else if (flag and 2) then
  ALTERNATE DEFINE main ship: flag = flag or 2
end if
end if

if energybar_needs_update then
if (flag and 3 = 3) then 
    postpone update for energybar
else if (flag and 1) then
   DEFINE energybar: flag = flag or 1
else if (flag and 2) then
  ALTERNATE DEFINE energybar: flag = flag or 2
end if
end if

Same for boss animation etc etc

goto mainloop

**Comment by nanochess** [comment]
Your code could crash when 3 sets are defined at same time. Currently no bookkeeping planed.
